### ISSUE TITLE
php craft make module breaks craft console

### ISSUE THREAD

**Issue by zadro** [craftcms/generator#11]
Hello, thanks for streamlining the module/plugin scaffolding! I'm still learning how to use it, so please let me know if I missed something. 

In short, after running: `php craft make module` and creating a controller for the module, I can no longer run `php craft` to get the standard list of available console options.

Error below when running `php craft` from the command line:

Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @modules/console/controllers'

in /home/user/craft/vendor/yiisoft/yii2/BaseYii.php:154

**Comment by brandonkelly** [comment]
If the command had to define a new `autoload` root in `composer.json`, then you need to run the following command after it’s done:

```sh
composer dump-autoload
```

**Comment by zadro** [comment]
Thanks, Brandon. Unfortunately, that didn't work. Please see below. Something else I might be missing? This is a clean/new install with Craft 4.3.5 and nothing else.

user@web:~/craft$ composer dump-autoload
Generating optimized autoload files
Generated optimized autoload files containing 4675 classes
user@web:~/craft$ php craft
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @modules/test/console/controllers'

in /home/user/craft/vendor/yiisoft/yii2/BaseYii.php:154

**Comment by brandonkelly** [comment]
Can you post the contets of the following files?

- `composer.json`
- `config/app.php`
- `modules/test/Module.php`

**Comment by almeric** [comment]
I have the same problem.

Simple reproduction:

```bash
./craft make module
Module ID: (kebab-case) test-module
Module location: modules/test
Should the module be loaded during app initialization? (yes|no) [no]:
 → Creating modules/test/ … ✓
 → Creating modules/test/Module.php … ✓
 → Updating config/app.php … ✓

✅ Module created!

```

`modules/test/Module.php`:

```php
<?php

namespace modules\test;

use Craft;
use yii\base\Module as BaseModule;

/**
 * test-module module
 *
 * @method static Module getInstance()
 */
class Module extends BaseModule
{
    public function init()
    {
        // Set the controllerNamespace based on whether this is a console or web request
        if (Craft::$app->request->isConsoleRequest) {
            $this->controllerNamespace = 'modules\\test\\console\\controllers';
        } else {
            $this->controllerNamespace = 'modules\\test\\controllers';
        }

        parent::init();

        // Defer most setup tasks until Craft is fully initialized
        Craft::$app->onInit(function() {
            $this->attachEventHandlers();
            // ...
        });
    }

    private function attachEventHandlers(): void
    {
        // Register event handlers here ...
        // (see https://craftcms.com/docs/4.x/extend/events.html to get started)
    }
}
```

`config/app.php`:

```php
<?php
/**
 * Yii Application Config
 *
 * Edit this file at your own risk!
 *
 * The array returned by this file will get merged with
 * vendor/craftcms/cms/src/config/app.php and app.[web|console].php, when
 * Craft's bootstrap script is defining the configuration for the entire
 * application.
 *
 * You can define custom modules and system components, and even override the
 * built-in system components.
 *
 * If you want to modify the application config for *only* web requests or
 * *only* console requests, create an app.web.php or app.console.php file in
 * your config/ folder, alongside this one.
 *
 * Read more about application configuration:
 * https://craftcms.com/docs/4.x/config/app.html
 */

use craft\helpers\App;
use modules\test\Module;

return [
    'id'        => App::env('CRAFT_APP_ID') ?: 'CraftCMS',
    'modules'   => [
        'test-module' => Module::class,
    ],
];

```

`composer.json`:

```json
{
  "require": {
    "craftcms/cms": "^4.3.5",
    "craftcms/feed-me": "^5.0",
    "craftcms/redactor": "^3.0",
    "nystudio107/craft-imageoptimize": "^4.0",
    "nystudio107/craft-minify": "^4.0.0-beta.2",
    "nystudio107/craft-vite": "4.0.5",
    "sebastianlenz/linkfield": "^2.1",
    "verbb/navigation": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "craftcms/generator": "^1.2",
    "nystudio107/craft-autocomplete": "^1.11",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.0.2"
    }
  },
  "scripts": {
    "craft-update": [
      "@pre-craft-update",
      "@post-craft-update"
    ],
    "pre-craft-update": [
    ],
    "post-craft-update": [
      "Composer\\Config::disableProcessTimeout",
      "@php craft install/check && php craft clear-caches/all --interactive=0 || exit 0",
      "@php craft install/check && php craft up --interactive=0 || exit 0"
    ],
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\""
    ]
  }
}

```

I get the following exception:

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @modules/test/console/controllers'

in /var/www/html/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Module.php(261): yii\BaseYii::getAlias('@modules/test/c...')
#1 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(245): yii\base\Module->getControllerPath()
#2 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(240): yii\console\controllers\HelpController->getModuleCommands(Object(modules\test\Module))
#3 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(172): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#4 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(192): yii\console\controllers\HelpController->getCommands()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(292): yii\console\controllers\HelpController->getCommandDescriptions()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/HelpController.php(87): yii\console\controllers\HelpController->actionIndex(NULL)
#8 [internal function]: craft\console\controllers\HelpController->actionIndex(NULL)
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#18 /var/www/html/craft(13): yii\base\Application->run()
#19 {main}
```

I can fix it by adding the following to the generated module:

```php
public function __construct($id, $parent = null, $config = [])
{
    parent::__construct($id, $parent, $config);
    Craft::setAlias('@modules/test/console/controllers', __DIR__);
}
```

**Comment by brandonkelly** [comment]
Aha, thanks for the stack trace, @almeric! Just released v1.2.2 with a fix.

You should be naming your alias `modules/test` rather than `@modules/test/console/controllers`.

**Comment by brandonkelly** [comment]
@zadro In your case, you can fix by adding the following line to the beginning of your module’s `init()` method:

```php
Craft::setAlias('@module/namespace', __DIR__);
```

(Replace `module/namespace` with your module’s actual namespace, pulled from the top of the file, except with `\`s replaced with `/`s.)

**Comment by almeric** [comment]
@brandonkelly Thanks!

**Comment by zadro** [comment]
@brandonkelly Thank you!!
