### ISSUE TITLE
Make module error

### ISSUE THREAD

**Issue by iZerus** [craftcms/generator#16]
### Description
When trying to create a module, it gives an error:
```
Module ID: (kebab-case) pdfaker
Exception 'yii\base\InvalidArgumentException' with message '`W:/domains/craft.gymfit.test/W:/domains/craft.gymfit.test/composer.json` doesn’t exist.'

in W:\domains\craft.gymfit.test\vendor\craftcms\cms\src\helpers\Json.php:64

Stack trace:
#0 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\helpers\Composer.php(32): craft\helpers\Json::decodeFromFile()
#1 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\helpers\Composer.php(77): craft\generator\helpers\Composer::autoloadConfigFromFile()
#2 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\BaseGenerator.php(377): craft\generator\helpers\Composer::couldAutoload()
#3 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\BaseGenerator.php(331): craft\generator\BaseGenerator->craft\generator\{closure}()
#4 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\BaseGenerator.php(340): craft\generator\BaseGenerator->craft\generator\{closure}()
#5 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\BaseGenerator.php(386): craft\generator\BaseGenerator->directoryPrompt()
#6 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\generators\Module.php(43): craft\generator\BaseGenerator->autoloadableDirectoryPrompt()
#7 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\Command.php(260): craft\generator\generators\Module->run()
#8 [internal function]: craft\generator\Command->actionGenerate()
#9 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()#10 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams()
#11 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\console\Controller.php(180): yii\base\Controller->runAction()
#12 W:\domains\craft.gymfit.test\vendor\craftcms\cms\src\console\ControllerTrait.php(87): yii\console\Controller->runAction()
#13 W:\domains\craft.gymfit.test\vendor\craftcms\cms\src\console\Controller.php(217): craft\console\Controller->traitRunAction()
#14 W:\domains\craft.gymfit.test\vendor\craftcms\generator\src\Command.php(131): craft\console\Controller->runAction()
#15 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\base\Module.php(552): craft\generator\Command->runAction()
#16 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction()
#17 W:\domains\craft.gymfit.test\vendor\craftcms\cms\src\console\Application.php(90): yii\console\Application->runAction()
#18 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\console\Application.php(147): craft\console\Application->runAction()
#19 W:\domains\craft.gymfit.test\vendor\craftcms\cms\src\console\Application.php(121): yii\console\Application->handleRequest()
#20 W:\domains\craft.gymfit.test\vendor\yiisoft\yii2\base\Application.php(384): craft\console\Application->handleRequest()
#21 W:\domains\craft.gymfit.test\craft(13): yii\base\Application->run()
#22 {main}
```

Some kind of bug in the formation of the path:
```
Exception 'yii\base\InvalidArgumentException' with message '`W:/domains/craft.gymfit.test/W:/domains/craft.gymfit.test/composer.json` doesn’t exist.'
```

### Steps to reproduce

1. Cmd: `php craft make module`

### Additional info

- Craft version: Craft Pro 4.4.3
- PHP version: 8.1.9
- Database driver & version: MySQL 8.0.30
- Plugins & versions: Kint (3.1.0), Redactor (3.0.4)

**Comment by brandonkelly** [comment]
Is your Craft project missing a `composer.json` file? Or is it located somewhere besides `W:/domains/craft.gymfit.test/W:/domains/craft.gymfit.test/composer.json`?

**Comment by iZerus** [comment]
> Is your Craft project missing a `composer.json` file? Or is it located somewhere besides `W:/domains/craft.gymfit.test/W:/domains/craft.gymfit.test/composer.json`?

It is located along the path: `W:/domains/craft.gymfit.test/composer.json`

**Comment by brandonkelly** [comment]
Doh, I missed that the path had been doubled-up.

That ended up being a Craft CMS bug, which is now fixed for the next release.

If you’d like to get the fix early and re-test the module generation, change your `craftcms/cms` requirement in `composer.json` to `dev-develop#a5022cde1305d822daa2e12e7970693cf07f7e8d as 4.4.5`, and then run `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.4.6 is out now with that fix 🎉
